<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="LibreHardwareMonitorLib" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mazesta.Core/Mazesta.Core.csproj" />
    <ProjectReference Include="../../src/Mazesta.Hardware/Mazesta.Hardware.csproj" />
  </ItemGroup>
</Project>
