<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mazesta.Core/Mazesta.Core.csproj" />
    <ProjectReference Include="../../src/Mazesta.Monitoring/Mazesta.Monitoring.csproj" />
    <ProjectReference Include="../../src/Mazesta.Persistence/Mazesta.Persistence.csproj" />
    <ProjectReference Include="../../src/Mazesta.Diagnostics/Mazesta.Diagnostics.csproj" />
  </ItemGroup>
</Project>
